import type { Metadata } from "next";
import { SectionHeading } from "@/components/system/section-heading";
import { getSentinelDataSource } from "@/data/data-source";
import type { EvaluationChannel, EvaluationMetrics } from "@/domain/sentinel";

export const metadata: Metadata = { title: "Models" };
function percent(value: number) { return `${(value * 100).toFixed(1)}%`; }
function readable(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }

function Metrics({ metrics }: { metrics: EvaluationMetrics }) {
  return <dl className="grid grid-cols-2 border-l border-t border-border sm:grid-cols-4">{[["Precision", metrics.precision], ["Recall", metrics.recall], ["F1", metrics.f1], ["False positive rate", metrics.falsePositiveRate]].map(([label, value]) => <div key={String(label)} className="border-b border-r border-border p-3"><dt className="tech-label">{label}</dt><dd className="mt-1.5 font-mono text-[16px] tabular">{percent(Number(value))}</dd></div>)}</dl>;
}

function Coverage({ channel }: { channel: EvaluationChannel }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left"><caption className="sr-only">{channel.name} scenario coverage</caption><thead className="border-b border-border text-[9px] uppercase tracking-[0.1em] text-[var(--text-muted)]"><tr><th className="px-3 py-2" scope="col">Scenario</th><th className="px-3 py-2" scope="col">Detected</th><th className="px-3 py-2" scope="col">Total</th><th className="px-3 py-2" scope="col">Recall</th></tr></thead><tbody className="divide-y divide-border">{Object.entries(channel.scenarioCoverage).map(([scenario, coverage]) => <tr key={scenario}><td className="px-3 py-2.5 text-[11px]">{readable(scenario)}</td><td className="px-3 py-2.5 font-mono text-[10px]">{coverage.detected}</td><td className="px-3 py-2.5 font-mono text-[10px]">{coverage.total}</td><td className="px-3 py-2.5 font-mono text-[10px]">{percent(coverage.recall)}</td></tr>)}</tbody></table></div>;
}

export default async function ModelsPage() {
  const source = getSentinelDataSource();
  const [models, evaluation, quantum] = await Promise.all([source.listModels(), source.getModelEvaluation(), source.getQuantumEvaluation()]);
  return <div className="mx-auto max-w-[1500px] space-y-7">
    <section className="border-b border-border pb-5"><div className="tech-label">Sentinel / Detection</div><h1 className="mt-2 text-[22px] font-semibold tracking-[-0.025em]">Models</h1><p className="mt-1 max-w-3xl text-[12px] text-[var(--text-secondary)]">Reproducible detection metadata and held-out evaluation. Experimental results are evidence only and do not change the existing risk model.</p></section>
    <section className="space-y-3"><SectionHeading eyebrow="Runtime" title="Deployed model metadata" description="Configuration reported by the active SentinelAI service" /><div className="grid gap-3 lg:grid-cols-2">{models.map((model) => <article key={model.name} className="panel p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-[12px] font-semibold">{model.name}</h3><span className="rounded-sm border border-[var(--border-strong)] px-1.5 py-0.5 font-mono text-[9px] uppercase text-[var(--text-secondary)]">{model.status}</span></div><dl className="mt-4 grid grid-cols-2 gap-4 text-[10px]"><div><dt className="tech-label">Version</dt><dd className="mt-1 font-mono">{model.version ?? "Unavailable"}</dd></div><div><dt className="tech-label">Training rows</dt><dd className="mt-1 font-mono">{model.trainingRows ?? "Unavailable"}</dd></div><div className="col-span-2"><dt className="tech-label">Training scope</dt><dd className="mt-1 leading-4 text-[var(--text-secondary)]">{model.trainingScope ?? "Unavailable"}</dd></div><div className="col-span-2"><dt className="tech-label">Interpretation</dt><dd className="mt-1 leading-4 text-[var(--text-secondary)]">{model.anomalyDefinition ?? "Unavailable"}</dd></div></dl></article>)}</div></section>
    <section className="space-y-3"><SectionHeading eyebrow="Held-out benchmark" title="Classical and rules evaluation" description={evaluation?.dataset.strategy ?? "Evaluation execution requires live API mode."} />{evaluation ? <div className="space-y-4"><div className="grid gap-4 xl:grid-cols-2">{[evaluation.classical, evaluation.rules].map((channel) => <article key={channel.name} className="panel"><div className="border-b border-border p-4"><h3 className="text-[12px] font-semibold">{channel.name}</h3><p className="mt-1 font-mono text-[9px] text-[var(--text-muted)]">{channel === evaluation.classical ? evaluation.thresholds.classical : evaluation.thresholds.rules}</p></div><Metrics metrics={channel.metrics} /><Coverage channel={channel} /></article>)}</div><div className="panel p-4"><div className="tech-label">Dataset boundary</div><p className="mt-2 font-mono text-[10px] text-[var(--text-secondary)]">720 baseline · 240 training · 240 normal test · 108 suspicious test · future data used: NO</p><ul className="mt-3 space-y-1 text-[10px] text-[var(--text-muted)]">{evaluation.limitations.map((item) => <li key={item}>— {item}</li>)}</ul></div></div> : <div className="panel p-5 text-[11px] text-[var(--text-muted)]">The offline fixture contains model metadata but no precomputed evaluation report. Start the API and select HTTP data mode to run it.</div>}</section>
    <section className="space-y-3"><SectionHeading eyebrow="Experimental" title="Quantum kernel benchmark" description="Small Qiskit/Aer comparison; never included in production risk" />{quantum.status === "ready" && quantum.metrics && quantum.configuration ? <div className="space-y-4"><article className="panel"><div className="border-b border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-[12px] font-semibold">{quantum.label}</h3><p className="mt-1 text-[10px] text-[var(--text-muted)]">{quantum.implementation}</p></div><span className="rounded-sm border border-[var(--medium)]/50 px-2 py-1 font-mono text-[9px] text-[var(--medium)]">NO ADVANTAGE CLAIM</span></div></div><Metrics metrics={quantum.metrics} /><dl className="grid gap-3 border-t border-border p-4 text-[10px] sm:grid-cols-2 lg:grid-cols-4"><div><dt className="tech-label">Circuit</dt><dd className="mt-1">{quantum.configuration.featureMap} · {quantum.configuration.qubits} qubits</dd></div><div><dt className="tech-label">Sampling</dt><dd className="mt-1 font-mono">{quantum.configuration.shots} shots · seed {quantum.configuration.randomSeed}</dd></div><div><dt className="tech-label">Sample</dt><dd className="mt-1 font-mono">{quantum.configuration.trainingRows} train · {quantum.configuration.normalTestRows + quantum.configuration.anomalyTestRows} test</dd></div><div><dt className="tech-label">Runtime</dt><dd className="mt-1 font-mono">{quantum.runtimeSeconds?.toFixed(3)} s</dd></div></dl></article>
      <div className="panel overflow-x-auto"><table className="w-full min-w-[900px] text-left"><caption className="sr-only">Quantum and classical assessment comparison</caption><thead className="border-b border-border bg-[var(--surface-elevated)] text-[9px] uppercase tracking-[0.1em] text-[var(--text-muted)]"><tr><th className="px-3 py-2.5">Event</th><th className="px-3 py-2.5">Scenario</th><th className="px-3 py-2.5">Expected</th><th className="px-3 py-2.5">Classical</th><th className="px-3 py-2.5">Quantum</th><th className="px-3 py-2.5">Agreement</th><th className="px-3 py-2.5">Confidence</th></tr></thead><tbody className="divide-y divide-border">{quantum.assessments?.map((item) => <tr key={item.eventId}><td className="px-3 py-2.5 font-mono text-[10px]">{item.eventId}</td><td className="px-3 py-2.5 text-[10px]">{readable(item.scenario)}</td><td className="px-3 py-2.5 font-mono text-[10px]">{item.expectedAnomaly ? "ANOMALY" : "NORMAL"}</td><td className="px-3 py-2.5 font-mono text-[10px]">{item.classicalStatus} · {item.classicalScore?.toFixed(2) ?? "—"}</td><td className="px-3 py-2.5 font-mono text-[10px]">{item.quantumStatus} · {item.quantumScore?.toFixed(4) ?? "—"}</td><td className="px-3 py-2.5 font-mono text-[10px]">{item.agreement ? "YES" : "NO"}</td><td className="px-3 py-2.5 text-[10px] text-[var(--text-muted)]">Not calibrated</td></tr>)}</tbody></table></div><div className="panel p-4"><ul className="space-y-1 text-[10px] text-[var(--text-muted)]">{quantum.limitations?.map((item) => <li key={item}>— {item}</li>)}</ul></div></div> : <div className="panel border-[var(--medium)]/30 p-5 text-[11px] text-[var(--text-muted)]"><span className="font-semibold text-[var(--medium)]">UNAVAILABLE</span> · {quantum.reason ?? "Quantum benchmark did not return a result."}</div>}</section>
  </div>;
}
